version: "3"

networks:
  ff:
    driver: bridge

services:
  ff_movies:
    container_name: ff_movies
    image: node:lts
    volumes:
      - ./movies/api:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    env_file: ./movies/api/.env
    networks:
      - ff
